### PR TITLE
Jason add carousels

### PR DESCRIPTION
**Pull request by rgardner**

### CODE REVIEW

**Comment by rgardner** [comment]
I'm trying it out on my machine now.

**Comment by JasonYao** [comment]
This is what it looks like for me, we can still add left align if you like, but it looks much better than before since we made the div a constant width with the scroll bar

**Comment by JasonYao** [comment]
z.z i dunno why the image isn't showing since I selected it from both GUI and just the drag and drop, but here's a link to how the new expectations page looks
https://imgur.com/3976W1t

**Comment by JasonYao** [comment]
Also, I agree about reading the consitiution, I didn't realize how forceful it originally sounded: 
"please write to the Chi with a brief written explanation of what you feel attracts you to the Fraternity and how you would hope to involve yourself in its work"

I'll leave it for now and we can hash out a better sounding one after I finish up cleaning up the other pages

**Comment by rgardner** [comment]
on the image not showing, I thinnnk it's because you submitted the comment before letting it fully upload.

**Comment by rgardner** [comment]
I agree on the membership expectations page - much better! The constant width with scrollbar did the trick, nice!

**Comment by rgardner** [comment]
This looks great to me, thank you man!

**Pull request merged**
